### ISSUE TITLE
Implement Ocean V4 market dynamics, run simulations, tune until satisifed

### ISSUE THREAD

**Issue by trentmc** [tokenspice/tokenspice#29]
Prerequisite: #110 (get oceanv4 contracts, incl compiling), and ideally #111 (oceanv4 unit tests).

These don't need to be perfect, the main idea is to show that rug pulls happen in V3 and not in V4. Also IL is much lower in V4 because there isn't massive slippage when people stake OCEAN (and unstake).

- [ ] Observe Ocean V4 market dynamics: point at Ocean V4 contracts and run!
- [ ] Iterate on Ocean V4 sim and on design until satisfied

Helpful:
- v4 branch: https://github.com/oceanprotocol/contracts/tree/v4main
- v4 slides: https://docs.google.com/presentation/d/1JfFi9hT4Lf3UQKfCXGDhA27YPpPcWsXU7YArfRGAmMQ/edit#slide=id.p1

**Comment by trangnv** [comment]
**Update 15 Nov**

1. Deployed Ocean V4 contract, using [v4main branch](https://github.com/oceanprotocol/contracts/tree/v4main)
- With `npx hardhat node`
- With `./ganache`
Both worked (got deployed) but behave differently, not sure which one should be used

2. Deploy with `npx hardhat node`
- Stuck at `web3tools/web3wallet.py` line 128: `tx_hash = _web3.eth.send_raw_transaction(signed_tx.rawTransaction)`
with an error:
`ValueError: {'code': -32000, 'message': 'Transaction gasPrice (1) is too low for the next block, which has a baseFeePerGas of 104885781'}`

- That came from AgentWallet trying to get ETH to pay gas
`AgentWallet.py` line 39: `self._web3wallet.fundFromAbove(num_wei=toBase18(0.01))`

3. Deploy with `./ganache`
When deploying with ganache, that problem seems to go away, now AgentWallet tries to `mintOCEAN` but gets stuck in artifacts as v4 artifacts are different than v3

=> ***Trying this way***

4. Engine/web3engine
Now all files in engine and web3engine (bpool, dtfactory, btoken, bfactory, datatoken) are being shifted to use with what is in [ocean.py v4main branch](https://github.com/oceanprotocol/ocean.py/tree/v4main)

**Comment by trentmc** [comment]
I think you need to refactor the directories further.

- (rename) web3engine --> drivers-oceanv3
- (add) drivers -> oceanv4

And probably with many agents too.

**Comment by trangnv** [comment]
Yeah. I did the refactor and changing name, but will follow you suggestion for convenience.

**Comment by trentmc** [comment]
Could you make a PR so I can see the changes, please?

**Comment by trangnv** [comment]
I put the new branch up, not the best structure but I will change later.

**Comment by trentmc** [comment]
Thanks @trangnv!

I will making comments in the PR now, versus here.
